#!/usr/bin/env python
"""
WordAPI.py
Copyright 2014 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from models import *


class ResourcesApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    

    def getResources(self, **kwargs):
        """Read all IT Component

        Args:
            relations, bool: If set to true, all relations of the Fact Sheet are fetched as well. Fetching all relations can be slower. Default: false. (optional)

            filter, str: Full-text filter (optional)

            

        Returns: Array[Resource]
        """

        allParams = ['relations', 'filter']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getResources" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('relations' in params):
            queryParams['relations'] = self.apiClient.toPathValue(params['relations'])
        if ('filter' in params):
            queryParams['filter'] = self.apiClient.toPathValue(params['filter'])
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Array[Resource]')
        return responseObject
        

        

    def createResource(self, **kwargs):
        """Create a new IT Component

        Args:
            body, Resource: Message-Body (optional)

            

        Returns: Resource
        """

        allParams = ['body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method createResource" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Resource')
        return responseObject
        

        

    def getResource(self, ID, **kwargs):
        """Read a IT Component by a given ID

        Args:
            ID, str: Unique ID (required)

            relations, bool: If set to true, all relations of the Fact Sheet are fetched as well. Fetching all relations can be slower. Default: false. (optional)

            

        Returns: Resource
        """

        allParams = ['ID', 'relations']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getResource" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('relations' in params):
            queryParams['relations'] = self.apiClient.toPathValue(params['relations'])
        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Resource')
        return responseObject
        

        

    def updateResource(self, ID, **kwargs):
        """Update a IT Component by a given ID

        Args:
            ID, str: Unique ID (required)

            body, Resource: Message-Body (optional)

            

        Returns: Resource
        """

        allParams = ['ID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method updateResource" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Resource')
        return responseObject
        

        

    def deleteResource(self, ID, **kwargs):
        """Delete a IT Component by a given ID

        Args:
            ID, str: Unique ID (required)

            

        Returns: 
        """

        allParams = ['ID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method deleteResource" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        

        

    def getFactSheetHasParents(self, ID, **kwargs):
        """Read all of relation

        Args:
            ID, str: Unique ID (required)

            

        Returns: Array[FactSheetHasParent]
        """

        allParams = ['ID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFactSheetHasParents" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasParents'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Array[FactSheetHasParent]')
        return responseObject
        

        

    def createFactSheetHasParent(self, ID, **kwargs):
        """Create a new relation

        Args:
            ID, str: Unique ID (required)

            body, FactSheetHasParent: Message-Body (optional)

            

        Returns: FactSheetHasParent
        """

        allParams = ['ID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method createFactSheetHasParent" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasParents'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasParent')
        return responseObject
        

        

    def getFactSheetHasParent(self, ID, relationID, **kwargs):
        """Read by relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: FactSheetHasParent
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFactSheetHasParent" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasParents/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasParent')
        return responseObject
        

        

    def updateFactSheetHasParent(self, ID, relationID, **kwargs):
        """Update relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            body, FactSheetHasParent: Message-Body (optional)

            

        Returns: FactSheetHasParent
        """

        allParams = ['ID', 'relationID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method updateFactSheetHasParent" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasParents/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasParent')
        return responseObject
        

        

    def deleteFactSheetHasParent(self, ID, relationID, **kwargs):
        """Delete relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: 
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method deleteFactSheetHasParent" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasParents/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        

        

    def getFactSheetHasChildren(self, ID, **kwargs):
        """Read all of relation

        Args:
            ID, str: Unique ID (required)

            

        Returns: Array[FactSheetHasChild]
        """

        allParams = ['ID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFactSheetHasChildren" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasChildren'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Array[FactSheetHasChild]')
        return responseObject
        

        

    def createFactSheetHasChild(self, ID, **kwargs):
        """Create a new relation

        Args:
            ID, str: Unique ID (required)

            body, FactSheetHasChild: Message-Body (optional)

            

        Returns: FactSheetHasChild
        """

        allParams = ['ID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method createFactSheetHasChild" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasChildren'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasChild')
        return responseObject
        

        

    def getFactSheetHasChild(self, ID, relationID, **kwargs):
        """Read by relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: FactSheetHasChild
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFactSheetHasChild" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasChildren/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasChild')
        return responseObject
        

        

    def updateFactSheetHasChild(self, ID, relationID, **kwargs):
        """Update relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            body, FactSheetHasChild: Message-Body (optional)

            

        Returns: FactSheetHasChild
        """

        allParams = ['ID', 'relationID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method updateFactSheetHasChild" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasChildren/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasChild')
        return responseObject
        

        

    def deleteFactSheetHasChild(self, ID, relationID, **kwargs):
        """Delete relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: 
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method deleteFactSheetHasChild" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasChildren/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        

        

    def getResourceHasProviders(self, ID, **kwargs):
        """Read all of relation

        Args:
            ID, str: Unique ID (required)

            

        Returns: Array[ResourceHasProvider]
        """

        allParams = ['ID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getResourceHasProviders" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/resourceHasProviders'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Array[ResourceHasProvider]')
        return responseObject
        

        

    def createResourceHasProvider(self, ID, **kwargs):
        """Create a new relation

        Args:
            ID, str: Unique ID (required)

            body, ResourceHasProvider: Message-Body (optional)

            

        Returns: ResourceHasProvider
        """

        allParams = ['ID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method createResourceHasProvider" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/resourceHasProviders'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ResourceHasProvider')
        return responseObject
        

        

    def getResourceHasProvider(self, ID, relationID, **kwargs):
        """Read by relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: ResourceHasProvider
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getResourceHasProvider" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/resourceHasProviders/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ResourceHasProvider')
        return responseObject
        

        

    def updateResourceHasProvider(self, ID, relationID, **kwargs):
        """Update relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            body, ResourceHasProvider: Message-Body (optional)

            

        Returns: ResourceHasProvider
        """

        allParams = ['ID', 'relationID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method updateResourceHasProvider" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/resourceHasProviders/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ResourceHasProvider')
        return responseObject
        

        

    def deleteResourceHasProvider(self, ID, relationID, **kwargs):
        """Delete relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: 
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method deleteResourceHasProvider" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/resourceHasProviders/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        

        

    def getResourceHasResourceCapabilities(self, ID, **kwargs):
        """Read all of relation

        Args:
            ID, str: Unique ID (required)

            

        Returns: Array[ResourceHasResourceCapability]
        """

        allParams = ['ID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getResourceHasResourceCapabilities" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/resourceHasResourceCapabilities'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Array[ResourceHasResourceCapability]')
        return responseObject
        

        

    def createResourceHasResourceCapability(self, ID, **kwargs):
        """Create a new relation

        Args:
            ID, str: Unique ID (required)

            body, ResourceHasResourceCapability: Message-Body (optional)

            

        Returns: ResourceHasResourceCapability
        """

        allParams = ['ID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method createResourceHasResourceCapability" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/resourceHasResourceCapabilities'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ResourceHasResourceCapability')
        return responseObject
        

        

    def getResourceHasResourceCapability(self, ID, relationID, **kwargs):
        """Read by relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: ResourceHasResourceCapability
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getResourceHasResourceCapability" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/resourceHasResourceCapabilities/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ResourceHasResourceCapability')
        return responseObject
        

        

    def updateResourceHasResourceCapability(self, ID, relationID, **kwargs):
        """Update relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            body, ResourceHasResourceCapability: Message-Body (optional)

            

        Returns: ResourceHasResourceCapability
        """

        allParams = ['ID', 'relationID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method updateResourceHasResourceCapability" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/resourceHasResourceCapabilities/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ResourceHasResourceCapability')
        return responseObject
        

        

    def deleteResourceHasResourceCapability(self, ID, relationID, **kwargs):
        """Delete relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: 
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method deleteResourceHasResourceCapability" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/resourceHasResourceCapabilities/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        

        

    def getServiceHasResources(self, ID, **kwargs):
        """Read all of relation

        Args:
            ID, str: Unique ID (required)

            

        Returns: Array[ServiceHasResource]
        """

        allParams = ['ID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getServiceHasResources" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/serviceHasResources'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Array[ServiceHasResource]')
        return responseObject
        

        

    def createServiceHasResource(self, ID, **kwargs):
        """Create a new relation

        Args:
            ID, str: Unique ID (required)

            body, ServiceHasResource: Message-Body (optional)

            

        Returns: ServiceHasResource
        """

        allParams = ['ID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method createServiceHasResource" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/serviceHasResources'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ServiceHasResource')
        return responseObject
        

        

    def getServiceHasResource(self, ID, relationID, **kwargs):
        """Read by relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: ServiceHasResource
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getServiceHasResource" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/serviceHasResources/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ServiceHasResource')
        return responseObject
        

        

    def updateServiceHasResource(self, ID, relationID, **kwargs):
        """Update relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            body, ServiceHasResource: Message-Body (optional)

            

        Returns: ServiceHasResource
        """

        allParams = ['ID', 'relationID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method updateServiceHasResource" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/serviceHasResources/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'ServiceHasResource')
        return responseObject
        

        

    def deleteServiceHasResource(self, ID, relationID, **kwargs):
        """Delete relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: 
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method deleteServiceHasResource" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/serviceHasResources/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        

        

    def getFactSheetHasDocuments(self, ID, **kwargs):
        """Read all of relation

        Args:
            ID, str: Unique ID (required)

            

        Returns: Array[FactSheetHasDocument]
        """

        allParams = ['ID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFactSheetHasDocuments" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasDocuments'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Array[FactSheetHasDocument]')
        return responseObject
        

        

    def createFactSheetHasDocument(self, ID, **kwargs):
        """Create a new relation

        Args:
            ID, str: Unique ID (required)

            body, FactSheetHasDocument: Message-Body (optional)

            

        Returns: FactSheetHasDocument
        """

        allParams = ['ID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method createFactSheetHasDocument" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasDocuments'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasDocument')
        return responseObject
        

        

    def getFactSheetHasDocument(self, ID, relationID, **kwargs):
        """Read by relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: FactSheetHasDocument
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFactSheetHasDocument" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasDocuments/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasDocument')
        return responseObject
        

        

    def updateFactSheetHasDocument(self, ID, relationID, **kwargs):
        """Update relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            body, FactSheetHasDocument: Message-Body (optional)

            

        Returns: FactSheetHasDocument
        """

        allParams = ['ID', 'relationID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method updateFactSheetHasDocument" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasDocuments/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasDocument')
        return responseObject
        

        

    def deleteFactSheetHasDocument(self, ID, relationID, **kwargs):
        """Delete relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: 
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method deleteFactSheetHasDocument" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasDocuments/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        

        

    def getFactSheetHasLifecycles(self, ID, **kwargs):
        """Read all of relation

        Args:
            ID, str: Unique ID (required)

            

        Returns: Array[FactSheetHasLifecycle]
        """

        allParams = ['ID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFactSheetHasLifecycles" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasLifecycles'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'Array[FactSheetHasLifecycle]')
        return responseObject
        

        

    def createFactSheetHasLifecycle(self, ID, **kwargs):
        """Create a new relation

        Args:
            ID, str: Unique ID (required)

            body, FactSheetHasLifecycle: Message-Body (optional)

            

        Returns: FactSheetHasLifecycle
        """

        allParams = ['ID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method createFactSheetHasLifecycle" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasLifecycles'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasLifecycle')
        return responseObject
        

        

    def getFactSheetHasLifecycle(self, ID, relationID, **kwargs):
        """Read by relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: FactSheetHasLifecycle
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getFactSheetHasLifecycle" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasLifecycles/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasLifecycle')
        return responseObject
        

        

    def updateFactSheetHasLifecycle(self, ID, relationID, **kwargs):
        """Update relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            body, FactSheetHasLifecycle: Message-Body (optional)

            

        Returns: FactSheetHasLifecycle
        """

        allParams = ['ID', 'relationID', 'body']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method updateFactSheetHasLifecycle" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasLifecycles/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'PUT'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        if ('' in params):
            bodyParam = params['']
        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'FactSheetHasLifecycle')
        return responseObject
        

        

    def deleteFactSheetHasLifecycle(self, ID, relationID, **kwargs):
        """Delete relation by a given relationID

        Args:
            ID, str: Unique ID (required)

            relationID, str: Unique ID of the Relation (required)

            

        Returns: 
        """

        allParams = ['ID', 'relationID']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method deleteFactSheetHasLifecycle" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/resources/{ID}/factSheetHasLifecycles/{relationID}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}
        formParams = {}
        bodyParam = None

        if ('ID' in params):
            replacement = str(self.apiClient.toPathValue(params['ID']))
            resourcePath = resourcePath.replace('{' + 'ID' + '}',
                                                replacement)
        if ('relationID' in params):
            replacement = str(self.apiClient.toPathValue(params['relationID']))
            resourcePath = resourcePath.replace('{' + 'relationID' + '}',
                                                replacement)
        if formParams:
            headerParams['Content-type'] = 'application/x-www-form-urlencoded'

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        

        

    




